DROP table review;
DROP table reply;
DROP table qa;
DROP table SITTER_review;
DROP table SITTER_REQUEST;
DROP table call;
DROP table OWNER_REQUEST;
DROP table SITTER_OPTION;
DROP table DIARY;
DROP table SITTING_OPTION;
DROP table ADMIN;
DROP table NOTICE;
DROP table SITTER_IMG;
DROP table pet;  
DROP table OWNER;
DROP table SITTER;
DROP table OPTIONS;

DROP SEQUENCE sequence_pet;
DROP SEQUENCE sequence_review;
DROP SEQUENCE sequence_qa;
DROP SEQUENCE sequence_reply;
DROP SEQUENCE sequence_SITTER_review;
DROP SEQUENCE sequence_CALL;
DROP SEQUENCE sequence_SITTER_REQUEST;
DROP SEQUENCE sequence_OWNER_REQUEST;
DROP SEQUENCE sequence_OPTIONS; 
DROP SEQUENCE sequence_SITTER_OPTION;
DROP SEQUENCE sequence_DIARY;
DROP SEQUENCE sequence_SITTING_OPTION;
DROP SEQUENCE sequence_NOTICE_ID;
DROP SEQUENCE sequence_SITTER_IMG_ID;

COMMIT;





COMMIT